--
-- PostgreSQL database dump DB clients
--

CREATE DATABASE clients;

-- Dumped from database version 11.15
-- Dumped by pg_dump version 11.15

-- Started on 2025-09-06 14:31:53

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO postgres;

--
-- TOC entry 2826 (class 0 OID 0)
-- Dependencies: 3
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: postgres
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_with_oids = false;

--
-- TOC entry 196 (class 1259 OID 161569)
-- Name: clients; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.clients (
    password integer NOT NULL,
    status boolean NOT NULL,
    client_id bigint NOT NULL
);


ALTER TABLE public.clients OWNER TO postgres;

--
-- TOC entry 198 (class 1259 OID 161576)
-- Name: persons; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.persons (
    age integer NOT NULL,
    person_id bigint NOT NULL,
    identification character varying(10) NOT NULL,
    phone character varying(10) NOT NULL,
    gender character varying(20) NOT NULL,
    address character varying(100) NOT NULL,
    name character varying(100) NOT NULL,
    CONSTRAINT persons_gender_check CHECK (((gender)::text = ANY ((ARRAY['MALE'::character varying, 'FEMALE'::character varying, 'OTHER'::character varying])::text[])))
);


ALTER TABLE public.persons OWNER TO postgres;

--
-- TOC entry 197 (class 1259 OID 161574)
-- Name: persons_person_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.persons ALTER COLUMN person_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.persons_person_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 2818 (class 0 OID 161569)
-- Dependencies: 196
-- Data for Name: clients; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2820 (class 0 OID 161576)
-- Dependencies: 198
-- Data for Name: persons; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2827 (class 0 OID 0)
-- Dependencies: 197
-- Name: persons_person_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.persons_person_id_seq', 1, false);


--
-- TOC entry 2691 (class 2606 OID 161573)
-- Name: clients clients_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.clients
    ADD CONSTRAINT clients_pkey PRIMARY KEY (client_id);


--
-- TOC entry 2693 (class 2606 OID 161583)
-- Name: persons persons_identification_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.persons
    ADD CONSTRAINT persons_identification_key UNIQUE (identification);


--
-- TOC entry 2695 (class 2606 OID 161581)
-- Name: persons persons_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.persons
    ADD CONSTRAINT persons_pkey PRIMARY KEY (person_id);


--
-- TOC entry 2696 (class 2606 OID 161584)
-- Name: clients fkpnhrp6ctlsaxqyge4owep2fqs; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.clients
    ADD CONSTRAINT fkpnhrp6ctlsaxqyge4owep2fqs FOREIGN KEY (client_id) REFERENCES public.persons(person_id);


-- Completed on 2025-09-06 14:31:53

--
-- PostgreSQL database dump complete
--


--
-- PostgreSQL database dump DB accounts
--

CREATE DATABASE accounts;

-- Dumped from database version 11.15
-- Dumped by pg_dump version 11.15

-- Started on 2025-09-06 14:30:43

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO postgres;

--
-- TOC entry 2830 (class 0 OID 0)
-- Dependencies: 3
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: postgres
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_with_oids = false;

--
-- TOC entry 197 (class 1259 OID 161591)
-- Name: accounts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.accounts (
    initial_balance numeric(38,2) NOT NULL,
    status boolean NOT NULL,
    account_id bigint NOT NULL,
    client_id bigint NOT NULL,
    account_type character varying(10) NOT NULL,
    number character varying(20) NOT NULL,
    CONSTRAINT accounts_account_type_check CHECK (((account_type)::text = ANY ((ARRAY['SAVINGS'::character varying, 'CHECKING'::character varying])::text[])))
);


ALTER TABLE public.accounts OWNER TO postgres;

--
-- TOC entry 196 (class 1259 OID 161589)
-- Name: accounts_account_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.accounts ALTER COLUMN account_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_account_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 199 (class 1259 OID 161601)
-- Name: movements; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.movements (
    balance numeric(38,2) NOT NULL,
    date date NOT NULL,
    value numeric(38,2) NOT NULL,
    account_id bigint NOT NULL,
    movement_id bigint NOT NULL,
    movement_type character varying(10) NOT NULL,
    CONSTRAINT movements_movement_type_check CHECK (((movement_type)::text = ANY ((ARRAY['WITHDRAWAL'::character varying, 'DEPOSIT'::character varying])::text[])))
);


ALTER TABLE public.movements OWNER TO postgres;

--
-- TOC entry 198 (class 1259 OID 161599)
-- Name: movements_movement_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.movements ALTER COLUMN movement_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.movements_movement_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 2822 (class 0 OID 161591)
-- Dependencies: 197
-- Data for Name: accounts; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2824 (class 0 OID 161601)
-- Dependencies: 199
-- Data for Name: movements; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2831 (class 0 OID 0)
-- Dependencies: 196
-- Name: accounts_account_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.accounts_account_id_seq', 1, false);


--
-- TOC entry 2832 (class 0 OID 0)
-- Dependencies: 198
-- Name: movements_movement_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.movements_movement_id_seq', 1, false);


--
-- TOC entry 2694 (class 2606 OID 161598)
-- Name: accounts accounts_number_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_number_key UNIQUE (number);


--
-- TOC entry 2696 (class 2606 OID 161596)
-- Name: accounts accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_pkey PRIMARY KEY (account_id);


--
-- TOC entry 2698 (class 2606 OID 161606)
-- Name: movements movements_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.movements
    ADD CONSTRAINT movements_pkey PRIMARY KEY (movement_id);


--
-- TOC entry 2699 (class 2606 OID 161607)
-- Name: movements fk1a6nru7corjv5b2vidld4ef5r; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.movements
    ADD CONSTRAINT fk1a6nru7corjv5b2vidld4ef5r FOREIGN KEY (account_id) REFERENCES public.accounts(account_id);


-- Completed on 2025-09-06 14:30:43

--
-- PostgreSQL database dump complete
--

