server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/krismaggot1991/EvaluacionUpgradeBP2025
          search-paths:
            - configuration
          clone-on-start: true

management:
  endpoints:
    web:
      exposure:
        include: health,info