eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka

server:
  port: 8222

spring:
  cloud:
    gateway:
      routes:
          - id: client
            uri: http://client:8090
            predicates:
              - Path=/api/client/**
          - id: account
            uri: http://account:8070
            predicates:
              - Path=/api/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials Access-Control-Expose-Headers, RETAIN_UNIQUE
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:8080"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            exposedHeaders: "*"
            allowCredentials: true